import productImage1 from '../assets/images/productImage1.png'
import productImage2 from '../assets/images/productImage2.png'
import productImage3 from '../assets/images/productImage3.png'
import productImage4 from '../assets/images/productImage4.png'
import productImage5 from '../assets/images/productImage5.png'
import productImage6 from '../assets/images/productImage6.png'
import productImage7 from '../assets/images/productImage7.png'
import productImage8 from '../assets/images/productImage8.png'

export const ProductSliderItems = [
	{
		id: 0,
		image: productImage1,
		title: 'Breed Dry Dog Food',
		currentPrice: 100,
		rating: 3,
		comments: 35,
	},
	{
		id: 1,
		image: productImage2,
		title: 'CANON EOS DSLR Camera',
		currentPrice: 360,
		rating: 4,
		comments: 95,
	},
	{
		id: 2,
		image: productImage3,
		title: 'ASUS FHD Gaming Laptop',
		currentPrice: 700,
		rating: 5,
		comments: 325,
	},
	{
		id: 3,
		image: productImage4,
		title: 'Curology Product Set',
		currentPrice: 500,
		rating: 4,
		comments: 145,
	},
	{
		id: 4,
		image: productImage5,
		title: 'HKids Electric Car',
		currentPrice: 950,
		rating: 5,
		comments: 65,
		colors: ['#FB1314', '#DB4444'],
		isNew: true,
	},
	{
		id: 5,
		image: productImage6,
		title: 'Jr. Zoom Soccer Cleats',
		currentPrice: 1160,
		rating: 5,
		comments: 35,
		colors: ['#EEFF61', '#DB4444'],
	},
	{
		id: 6,
		image: productImage7,
		title: 'GP11 Shooter USB Gamepad',
		currentPrice: 660,
		rating: 4.5,
		comments: 55,
		colors: ['#000000', '#DB4444'],
		isNew: true,
	},
	{
		id: 7,
		image: productImage8,
		title: 'Quilted Satin Jacket',
		currentPrice: 660,
		rating: 4.5,
		comments: 55,
		colors: ['#000000', '#DB4444'],
	},
	{
		id: 0,
		image: productImage1,
		title: 'Breed Dry Dog Food',
		currentPrice: 100,
		rating: 3,
		comments: 35,
	},
	{
		id: 1,
		image: productImage2,
		title: 'CANON EOS DSLR Camera',
		currentPrice: 360,
		rating: 4,
		comments: 95,
	},
	{
		id: 2,
		image: productImage3,
		title: 'ASUS FHD Gaming Laptop',
		currentPrice: 700,
		rating: 5,
		comments: 325,
	},
	{
		id: 3,
		image: productImage4,
		title: 'Curology Product Set',
		currentPrice: 500,
		rating: 4,
		comments: 145,
	},
	{
		id: 4,
		image: productImage5,
		title: 'HKids Electric Car',
		currentPrice: 950,
		rating: 5,
		comments: 65,
		colors: ['#FB1314', '#DB4444'],
		isNew: true,
	},
	{
		id: 5,
		image: productImage6,
		title: 'Jr. Zoom Soccer Cleats',
		currentPrice: 1160,
		rating: 5,
		comments: 35,
		colors: ['#EEFF61', '#DB4444'],
	},
	{
		id: 6,
		image: productImage7,
		title: 'GP11 Shooter USB Gamepad',
		currentPrice: 660,
		rating: 4.5,
		comments: 55,
		colors: ['#000000', '#DB4444'],
		isNew: true,
	},
	{
		id: 7,
		image: productImage8,
		title: 'Quilted Satin Jacket',
		currentPrice: 660,
		rating: 4.5,
		comments: 55,
		colors: ['#000000', '#DB4444'],
	},
]
