import todaySliderImage1 from '../assets/images/todaySlider1.png'
import todaySliderImage2 from '../assets/images/todaySlider2.png'
import todaySliderImage3 from '../assets/images/todaySlider3.png'
import todaySliderImage4 from '../assets/images/todaySlider4.png'

export const TodaySliderItems = [
	{
		id: 0,
		image: todaySliderImage1,
		title: 'HAVIT HV-G92 Gamepad',
		discount: 40,
		currentPrice: 120,
		oldPrice: 160,
		rating: 5,
		comments: 88,
	},
	{
		id: 1,
		image: todaySliderImage2,
		title: 'AK-900 Wired Keyboard',
		discount: 35,
		currentPrice: 960,
		oldPrice: 1160,
		rating: 4,
		comments: 75,
	},
	{
		id: 2,
		image: todaySliderImage3,
		title: 'IPS LCD Gaming Monitor',
		discount: 30,
		currentPrice: 370,
		oldPrice: 400,
		rating: 5,
		comments: 99,
	},
	{
		id: 3,
		image: todaySliderImage4,
		title: 'S-Series Comfort Chair ',
		discount: 25,
		currentPrice: 375,
		oldPrice: 400,
		rating: 4.5,
		comments: 99,
	},
	{
		id: 4,
		image: todaySliderImage1,
		title: 'HAVIT HV-G92 Gamepad',
		discount: 40,
		currentPrice: 120,
		oldPrice: 160,
		rating: 5,
		comments: 88,
	},
	{
		id: 5,
		image: todaySliderImage2,
		title: 'AK-900 Wired Keyboard',
		discount: 35,
		currentPrice: 960,
		oldPrice: 1160,
		rating: 4,
		comments: 75,
	},
	{
		id: 6,
		image: todaySliderImage3,
		title: 'IPS LCD Gaming Monitor',
		discount: 30,
		currentPrice: 370,
		oldPrice: 400,
		rating: 5,
		comments: 99,
	},
	{
		id: 7,
		image: todaySliderImage4,
		title: 'S-Series Comfort Chair ',
		discount: 25,
		currentPrice: 375,
		oldPrice: 400,
		rating: 4.5,
		comments: 99,
	},
]
